<?php
define('PACKAGES_TITLE',__('Manage Price Packages',DOMAIN));
define('ADD_A_PACKAGE_LINK',__('Add New Package',DOMAIN));
define('MONETIZATION_SETTINGS',__('Monetization Settings',DOMAIN));
define('ADD_NEW',__('Add New Package',DOMAIN));
define('ADD_NEW_DESC',__('Here are the currency settings where you can set the currency code, currency symbol and currency position for your domain',DOMAIN));
define('ADD_NEW_PACKAGE_DESC',__('A new package will be generated after you fill up the below information. These packages will allow you to charge the users to submit posts on your site',DOMAIN));
define('PACKAGE_LIST_DESC',__('Price Packages allow you to monetize your submission form and make money. For more on how they work visit the <a href="http://templatic.com/docs/tevolution-guide/#price_packages" title="Price Packages" target="_blank">Tevolution guide</a>',DOMAIN));
define('YES',__('Yes',DOMAIN));
define('NO',__('No',DOMAIN));
define('ACTIVE',__('Active',DOMAIN));
define('INACTIVE',__('Inactive',DOMAIN));
define('REQUIRED_TEXT',__('*',DOMAIN));
define('PACKAGE_TITLE',__('Title',DOMAIN));
define('PACKAGE_NAME_DESC',__('The package name will be shown inside the submission form. Feel free to get creative',DOMAIN));
define('PER_POST_DESC',__('Enable this option if you want users to pay for each submission.',DOMAIN));
define('PER_SUBSCRIPTION_DESC',__('This option creates a subscription that allows members to submit a preset number of listings in a set amount of time.',DOMAIN));
define('PACKAGE_CATEGORIES',__('Select Categories',DOMAIN));
define('PACKAGE_CATEGORIES_DESC',__('This package will be displayed for the selected categories',DOMAIN));
define('PACKAGE_DESC_TITLE',__('Package Description',DOMAIN));
define('PACKAGE_DESC',__('In few words, describe what this packages is about',DOMAIN));
define('SHOW_PACKAGE',__('Show Package',DOMAIN));
define('SHOW_PACKAGE_TITLE',__('Show Package even when no category is selected',DOMAIN));
define('SHOW_PACKAGE_DESC',__('Check the above box if you want the price package to show at all times',DOMAIN));
define('SELECT_POST_TYPES',__('Select Post Type',DOMAIN));
define('POST_TYPE_DESC',__('This package will be enabled for the selected post type',DOMAIN));
define('PACKAGE_AMOUNT',__('Amount',DOMAIN));
define('PRICE_AMOUNT_DESC',__("Enter the price of your package. It's the amount members will have to pay in order to purchase the package",DOMAIN));
define('BILLING_PERIOD',__('Billing Period',DOMAIN));
define('BILLING_PERIOD_DESC',__('Time between each billing. Enter numeric value or words. <strong>Tip:</strong> Numeric value will be more readable on your site.',DOMAIN));
define('DAYS_TEXT',__('Days',DOMAIN));
define('MONTHS_TEXT',__('Months',DOMAIN));
define('YEAR_TEXT',__('Years',DOMAIN));
define('PACKAGE_STATUS',__('Enable Package',DOMAIN));
define('PACKAGE_STATUS_DESC',__('Check marking it this will activate this package on your site',DOMAIN));
define('IS_RECURRING',__('Is Recurring',DOMAIN));
define('RECURRING_DESC',__('If "Yes" is selected, members will be billed automatically as soon as the price package (billing period) expires.',DOMAIN));
define('CHARGE_USER',__('Charge users every',DOMAIN));
define('RECURRING_BILLING_PERIOD',__('Billing Period for Recurring package',DOMAIN));
define('RECURRING_BILLING_PERIOD_DESC',__('Time between each billing',DOMAIN));
define('RECURRING_BILLING_CYCLE',__('Billing Cycle',DOMAIN));
define('RECURRING_BILLING_CYCLE_DESC',__('The number of times members will be billed, i.e. the number of times the process will be repeated',DOMAIN));
define('SETTINGS_FOR_FEATURED',__('Settings For Featured Entries',DOMAIN));
define('SETTINGS_FOR_FEATURED_DESC',__('These settings are must if you want to charge the users for featured posts otherwise leave them blank',DOMAIN));
define('SETTINGS_FOR_THOUGHTFUL_COMMENT',__('Comment Moderation',DOMAIN));
define('SETTINGS_FOR_THOUGHTFUL_COMMENT_DESC',__('Allows people to moderate comments on your site which came on the entries they submitted',DOMAIN));
define('CAN_AUTHOR_MODERATE',__('Allow author to moderate comments?',DOMAIN));
define('THOUGHTFUL_COMMENT_STATUS_DESC',__('Check the above option to define additional prices to author for moderating the comment of his post.',DOMAIN));
define('THOUGHTFUL_COMMENT_CHARGE',__('Amount to be charged for Comment moderation',DOMAIN));
define('IS_FEATURED',__('Is Featured',DOMAIN));
define('FEATURED_STATUS_DESC',__('Check the above option to define additional prices for featuring the listing on homepage and category pages',DOMAIN));
define('FEATURED_AMOUNT_HOME',__('Amount to be charged for Home page',DOMAIN));
define('FEATURED_AMOUNT_HOME_DESC',__('Mention the amount to charge extra for home page featured posts',DOMAIN));
define('FEATURED_AMOUNT_CAT',__('Amount to be charged for Category page',DOMAIN));
define('FEATURED_AMOUNT_CAT_DESC',__('Mention the amount to charge extra for category listing page featured posts',DOMAIN));
define('BACK_LINK_TEXT',__('Back to packages list',DOMAIN));
define('ACTION',__('Action',DOMAIN));
define('PACKAGE_DETAILS',__('Package Detail',DOMAIN));
define('EDIT_PACKAGE',__('Edit Package',DOMAIN));
define('DELETE_PACKAGE',__('Delete Package',DOMAIN));
define('NO_PACKAGE_AVAIL',__('You have not inserted any package yet',DOMAIN));
define('PACKAGE_TYPE',__('Package Type',DOMAIN));
define('PAY_PER_POST',__('Pay per Post',DOMAIN));
define('PAY_PER_SUB',__('Pay per Subscription',DOMAIN));
define('LIMIT_NO_POST',__('Number of Posts',DOMAIN));
define('NO_POST_DESC',__('Enter the number of posts members can submit with this price package, e.g. 10',DOMAIN));
define('VALIDITY_TEXT',__('Validity',DOMAIN));
define('PACKAGE_COST',__('Charges',DOMAIN));
define('PACKAGE_CYCLE',__('Recurring Charges',DOMAIN));
define('SELECT_PACKAGE_TEXT',__('Select a Package',DOMAIN));
define('CURRENCY_SYMB',__('Currency',DOMAIN));
define('CURRENCY_SYMB_DESC',__('You can specify the currency symbol here',DOMAIN));
define('CURRENCY_CODE',__('Currency Code',DOMAIN));
define('CURRENCY_CODE_DESC',__('Not sure which code to enter? Click <a href="http://www.xe.com/iso4217.php" title="Currency Codes" target="_blank">here</a>',DOMAIN));
define('CURRENCY_POS',__('Currency Position',DOMAIN));
define('CURRENCY_POS_DESC',__('You can set the currency position from here',DOMAIN));
define('SYMB_BFR_AMT',__('Use currency symbol as prefix',DOMAIN));
define('SPACE_BET_BFR_AMT',__('Space between amount and prefixed symbol',DOMAIN));
define('SYM_AFTR_AMT',__('Use currency symbol as Suffix',DOMAIN));
define('SPACE_BET_AFTR_AMT',__('Space between amount and suffixed symbol',DOMAIN));
define('FEATURED_TITLE',__('Would you like to make this post Featured?',DOMAIN));
define('FEATURED_HOME',__('Make this post featured on Home page',DOMAIN));
define('FEATURED_CAT',__('Make this post featured on Category listing page',DOMAIN));
define('MODERATE_COMMENT',__('Allow me to moderate comments of this entry.',DOMAIN));
define('FEATURED_MSG_DESC',__('An additional charges will be applied to make this post featured on any of the pages',DOMAIN));
define('TOTAL_CHARGES_TEXT',__('Total Charges',DOMAIN));
define('FEATURE_HEAD_TITLE',__('Price settings for Featured listings',DOMAIN)); 
define('FEATURE_HEAD_NOTE',__('<p class="notes_spec">You might want to charge users extra amount for featured listings within this price package.</p> ',DOMAIN)); 
define('FEATURE_STATUS_NOTE',__('Activate/deactivate additional price settings for &raquofeatured&raquo listings.',DOMAIN)); 
define('FEATURE_AMOUNT_TITLE',__('Amount to be charged<br><small>(for featuring on homepage)</small>',DOMAIN)); 
define('FEATURE_AMOUNT_NOTE',__('This is the price you wish to charge extra for featuring a place or an event listing on the homepage. eg. 20',DOMAIN)); 
define('FEATURE_CAT_TITLE',__('Amount to be charged<br><small>(for featuring on categories page)</small>',DOMAIN)); 
define('FEATURE_CAT_NOTE',__('This is the price you wish to charge extra for a place or an event listing on category pages. eg. 12',DOMAIN)); 
define('STATUS_NOTE',__('This setting will activate / deactivate this price package.',DOMAIN));
define('RECENT_TRANSACTION_TEXT',__('Latest Transactions Report',DOMAIN));

/*submit page price packages */
define('SUBMIT_LISTING_DAYS_TEXT',__('You are going to submit a post for %s days',DOMAIN));
define('ENTER_EVENT',__('1. Enter Event Listing Details',DOMAIN));
define('PREVIEW_EVENT',__('2. Preview Event &amp; Payment',DOMAIN));
define('SUCCESS_EVENT',__('3. Event Successful',DOMAIN));
define('FEATURED_H',__('Yes &sbquo; feature this listing on homepage.',DOMAIN));
define('FEATURED_C',__('Yes &sbquo; feature this listing on category pages.',DOMAIN));
define('PRICE_PACKAGE_ERROR',__('Please Select Price Package',DOMAIN));
define('FEATURED_C_EVENT',__('Yes &sbquo; feature this event on category pages.',DOMAIN));
define('TOTAL_TEXT',__('Total price as per your selection.',DOMAIN));
define('ORDER_STATUS_TITLE',__('Order Status',DOMAIN));

/* PAYMENT OPTIONS */
define('APPROVED_TEXT',__('Approved',DOMAIN));
define('PENDING_MONI',__('Pending',DOMAIN));
define('PAYMENT_SUCCESS_TITLE',__('Payment Success',DOMAIN));
define('BACK_TO_OREDR_TITLE',__('Back to Orders Listing',DOMAIN));
define('ORDER_STATUS_SAVE_MSG',__('Order status changed successfully',DOMAIN));
define('PAYMENT_SUCCESS_MSG','<h4>'.__("Your payment has been successfully received. The submitted content is now published.",DOMAIN).'</h4><p><a href="[#submited_information_link#]" >'.__("View your submitted information",DOMAIN).'</a></p><h5>'.__("Thank you for participating at",DOMAIN).' [#site_name#].</h5>');
define('INVALID_TRANSACTION_TITLE',__('Inavalid transation',DOMAIN));
define('INVALID_TRANSACTION_CONTENT',__('There is some error occured while transaction is being process, please try again.',DOMAIN));
define('AUTHENTICATION_CONTENT',__('Authentication fail, invalid transaction id generated.',DOMAIN));
define('PAY_CANCEL_MSG',__('Event Posting cancelled.<br><br>You can edit this message from language.php file at root of theme folder.',DOMAIN));
define('NEW_PAYMENT_GATEWAY_TITLE',__('Install New Payment Gateway',DOMAIN));
define('ORDER_UPDATE_TITLE',__('Update',DOMAIN));
define('MAIL_TO_FRIEND',__('Mail to friend',DOMAIN));
define('SEND_INQUIRY',__('Send inquiry',DOMAIN));

/*Transaction Report*/ 
define('TRANSACTION_REPORT_TEXT',__('Transaction Report',DOMAIN));
define('BACK_TO_TRANSACTION_LINK',__('Back to transaction list',DOMAIN));
define('TRANSACTION_REPORT_DESC',__('Here you can view the transaction detail.',DOMAIN));
define('COLOR',__('Color',DOMAIN));
define('ORDER_CANCEL_TEXT',__('Cancel',DOMAIN));

/* MANAGE COUPONS */
define('COUPON_DATE',__('Coupon Date',DOMAIN));
define('COUPON_ST_DATE',__('Coupon Start Date',DOMAIN));
define('COUPON_ST_DATE_DESC',__('Select date from which coupon will be active. After end date coupon will no longer work',DOMAIN));
define('COUPON_END_DATE',__('Coupon End Date',DOMAIN));
define('COUPON_END_DATE_DESC',__('Enter the end date. After this date the coupon will no longer work',DOMAIN));
define('COUPON_CODE_DESC',__('Mention coupon code.(It will act as a coupon verification key)',DOMAIN));
define('COUPON_TYPE_DESC',__('Choose how the discount should be calculated',DOMAIN));
define('COUPON_AMOUNT_DESC',__('Specify the discount amount.Values will be discounted based on the amount and the discount type selected in abve fields<br><strong>Note:</strong>Enter only numeric values for both amount type and percent type',DOMAIN));
define('PAID_AMOUNT',__('Paid amount',DOMAIN));
define('PAYMENT_METHOD',__('Payment Method',DOMAIN));
define('Status',__('Status',DOMAIN));
?>